module.exports = {
  cities: [
    "Chandigarh",
    "New Delhi",
    "Hyderabad",
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Gurgaon",
    "Bangalore",
    "Bengaluru",
    "Kochi",
    "Indore",
    "Mumbai",
    "Pune",
    "Jaipur",
    "Chennai",
    "Coimbatore",
    "Lucknow",
    "Noida",
    "Kolkata",
    "Thane",
    "Delhi",
  ],
  experienceOptions: ["0-2", "2-5", "5-8", "8-11", "11-14", "15+"],
};
